### PR TITLE
[compositor] set QPA_HWC_IDLE_TIME=5 in all compositor configurations. JB#45880

### PR DESCRIPTION
**Pull request by krnlyng**

### CODE REVIEW

**Comment by sledges** [comment]
Bugref missing in commit and also would be nice to refactor all common bits into droid-hal-device-sony-nile.conf :)

**Comment by krnlyng** [comment]
@sledges should i remove the device specific config files altogether and only keep droid-hal-config-sony-nile.conf?

**Comment by sledges** [comment]
> @sledges should i remove the device specific config files altogether and only keep droid-hal-config-sony-nile.conf?

You cannot remove them, because they contain differing display physical sizes

**Comment by krnlyng** [comment]
@sledges we could: https://github.com/mer-hybris/qt5-qpa-hwcomposer-plugin/commit/37428cd45040e8b2aaca95937e5313a4d92d8433

**Comment by sledges** [comment]
> @sledges we could: [mer-hybris/qt5-qpa-hwcomposer-plugin@37428cd](https://github.com/mer-hybris/qt5-qpa-hwcomposer-plugin/commit/37428cd45040e8b2aaca95937e5313a4d92d8433)

Please do if safe :)

**Pull request merged**
