### PR TITLE
Use own silica configs for discovery devices.

### PR DESCRIPTION
**Pull request by mkosola**
@Thaodan Could you test this on your XA2 Ultra?

### CODE REVIEW

**Comment by Thaodan** [comment]
Flashed the update now. Its definitely somewhat smaller. What I don't get why my old dpi was too small where I used the dpi used by android.

**Comment by Thaodan** [comment]
Can you explain why the dpi was lowered?

**Comment by mkosola** [comment]
You can calculate it here https://www.sven.de/dpi/ 6.0 inches and 1080 x 1920 pixels

**Comment by Thaodan** [comment]
Then I have no idea why Sony set the DPI higher than calculated.

**Pull request merged**
