### PR TITLE
[camera] Enable front flash for discovery MER#2043

### PR DESCRIPTION
**Pull request by Thaodan**
- make separate config with selfie flash/video torch enabled
- delete otherwise

### CODE REVIEW

**Comment by mkosola** [comment]
Can you squash commits? and also include bug number on commit?

**Comment by Thaodan** [comment]
> Can you squash commits? and also include bug number on commit?
Sure, I already added the bug numer in the line after it as on other bugs.
Should I squash all or just the first and the last?

**Comment by mkosola** [comment]
Ah, now noticed, it should contain [camera] at the same line as Contributes to MER#2043.
So it should be:
[camera] Enable flash for the front camera on discovery devices. Contributes to MER#2043.

And yes, you can have second as separate commit, so squash just first and the last. Thank you!

**Comment by Thaodan** [comment]
Should look better now.

**Comment by mkosola** [comment]
Thanks! Sorry to nag still, can you change commits order? Now the first commit is touching the file that is created only on the second commit.

**Comment by Thaodan** [comment]
No problem, done.

**Comment by mlehtima** [comment]
Typo in one of the commit messages "Enable flash for secondary camera on disovery." should have discovery not disovery.

**Comment by Thaodan** [comment]
Fixed

**Pull request merged**
