### PR TITLE
Delete ofono binder dual-sim config if it's there

### PR DESCRIPTION
**Pull request by monich**

### CODE REVIEW

**Comment by sledges** [comment]
I would keep this PR open (one for ganges too) and push the whole change eventually (submodule and pattern update, + removing `ril_subscription.d/dual-sim.conf`), so it's easier to track/revert in the future.

**Comment by monich** [comment]
I suggest to leave the ril_subscription stuff there, why not?

**Comment by sledges** [comment]
> I suggest to leave the ril_subscription stuff there

And by stuff you mean, the deletion of `dual-sim.conf`? :)

And what about `ril_subscription.conf` file itself? You nuked it here, so I thought you want to follow suit for devices that have their [own one](https://github.com/mer-hybris/droid-hal-configs/pull/246/files#r793904128).

**Comment by sledges** [comment]
> Delete ofono binder dual-sim config if it's there

I'm afraid the way we wrote it, rpmbuild won't like to attempt deleting a file that doesn't exist, so I think we might need an extra check here first: https://github.com/mer-hybris/droid-hal-configs/blob/35f69d3eb7941a8fedd29c5252a847f1d04cee52/droid-configs.inc#L331

**Comment by monich** [comment]
> > I suggest to leave the ril_subscription stuff there
> 
> And by stuff you mean, the deletion of `dual-sim.conf`? :)

Yes

> And what about `ril_subscription.conf` file itself? You nuked it [here](https://github.com/mer-hybris/droid-hal-configs/pull/246/files#diff-4de8737faed518b1d60bb7cc0d887af3efc13353f3797f12089bc42d71d36882), so I thought you want to follow suit for devices that have their [own one](https://github.com/mer-hybris/droid-hal-configs/pull/246/files#r793904128).

AFAIU those are device specific, meaning that there should never be both `binder.conf` and `ril_subscription.conf` in the image, it doesn't make sense (config has to match the plugin), i.e. whatever ofono .conf file is there, it stays there. And even if a wrong .conf file ends up in the image, it won't do any harm, ofono plugin will just ignore it. Unless I'm missing something again...

> I'm afraid the way we wrote it, rpmbuild won't like to attempt deleting a file that doesn't exist, so I think we might need an extra check here first: https://github.com/mer-hybris/droid-hal-configs/blob/35f69d3eb7941a8fedd29c5252a847f1d04cee52/droid-configs.inc#L331

Should it do `rm -f`?

**Review by sledges — APPROVED** [review]
> AFAIU those are device specific, meaning that there should never be both `binder.conf` and `ril_subscription.conf` in the image, it doesn't make sense (config has to match the plugin)

Ok then the removal (cleanup) of `ril_subscription.conf` from this and ganges repo add up to the checklist for the next PRs that will do the actual submodule update.

>> https://github.com/mer-hybris/droid-hal-configs/blob/35f69d3eb7941a8fedd29c5252a847f1d04cee52/droid-configs.inc#L331
> 
> Should it do `rm -f`?

Or check if file exists, but yes can go with `rm -f`.

**Review by sledges — CHANGES_REQUESTED** [review]
Pending the removal enforcing in [droid-hal-configs](https://github.com/mer-hybris/droid-hal-configs/blob/35f69d3eb7941a8fedd29c5252a847f1d04cee52/droid-configs.inc#L331).

**Comment by monich** [comment]
> Pending the removal enforcing in [droid-hal-configs](https://github.com/mer-hybris/droid-hal-configs/blob/35f69d3eb7941a8fedd29c5252a847f1d04cee52/droid-configs.inc#L331).

Would https://github.com/mer-hybris/droid-hal-configs/pull/247 do it?

**Comment by sledges** [comment]
> Would [mer-hybris/droid-hal-configs#247](https://github.com/mer-hybris/droid-hal-configs/pull/247) do it?

Yes, and since you will have to update submodule here, may I remind/suggest again to you of my [initial position](https://github.com/mer-hybris/droid-config-sony-nile/pull/141#issuecomment-1024270963) to keep this PR as WIP and rename it to "switch to ofono-binder-plugin", eventually committing all the other pieces of puzzle, once the main testing on x10ii has concluded.

Alternatively, I'm also ok with just updating the `rm -f` from submodule for now.

**Pull request closed without merging**
